# Generated by Django 5.2.5 on 2025-08-30 19:08

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ID_CARD', "Carte d'identité"), ('PASSPORT', 'Passeport'), ('DRIVER_LICENSE', 'Permis de conduire')], max_length=20, verbose_name='Type de document')),
                ('id_number', models.CharField(blank=True, max_length=64, verbose_name='Numéro du document')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('front_image', models.ImageField(upload_to=accounts.models.kyc_upload_path, validators=[accounts.models.validate_image_size], verbose_name='Document (recto)')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.kyc_upload_path, validators=[accounts.models.validate_image_size], verbose_name='Document (verso)')),
                ('selfie_image', models.ImageField(upload_to=accounts.models.kyc_upload_path, validators=[accounts.models.validate_image_size], verbose_name='Selfie avec document')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, verbose_name='Notes de revue (admin)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
